on: [push]
name: databrideployment1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      ResourceGroupName: test-rg
      ResourceGroupLocation: "eastus"
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.DATA_BRICKS}}
    - name: Checkout
      run: |
        sh ./moveFile.sh
        
